### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by Shane32**

### CODE REVIEW

**Comment by LeviGNMBS** [comment]
Hi Shane,

Is there anything blocking the update and publish a nuget package? I want to get rid from the annoying vulnerability messages ;)

Thanks!

**Comment by Shane32** [comment]
I don’t mind but this PR doesn’t pass the build checks so it can’t be merged as-is.

**Comment by Shane32** [comment]
Completed via:
- #9
- #10
- #11

**Comment by Shane32** [comment]
Version 4.5.3.10 was released with .NET 8 "compatibility".  Perhaps sometime I can make it use SkiaSharp to allow image manipulation on .NET 7+ running on Linux.

**Pull request closed without merging**
